elasticsearch:
  url: "http://10.0.4.205:9200/"
  index: "syslog-*"
  match: "Failed password for (?:root|invalid user [^ ]+) from ([^ ]+)"
  check_frequency: 1s
timeout: 1h
threshold: 5
stackdriver_project: "dparrish-com"
edgerouter:
  ip_port: 192.168.1.1:22
  ssh_key: /home/dparrish/.ssh/id_ecdsa
  user: dparrish
  address-group: rootblocker
