elasticsearch:
  url: "http://10.0.4.205:9200/"
  index: "filebeat-7.1.*"
  match: "Failed password for root from ([^ ]+)"
  check_frequency: 1s
timeout: 1h
threshold: 5
stackdriver_project: "dparrish-com"
